#!/usr/bin/env bash

#Makes the script safe

# -e stop if command fails 
# -u stop is var is missing 
# -o catch errors in the pipeline

set -euo pipefail

# setting dir variable & file 
REPORT_DIR="reports"
REPORT_FILE="$REPORT_DIR/system-report.txt"

# create directory if it does not exist -p 

mkdir -p "$REPORT_DIR"

# start the script fresh everytime the scrip runs we overide the report_file.
# we get the current / latest report. 
# We don't want to append anything as well we care about what is going on right now.

: > "$REPORT_FILE"

# Creates the header for each section 
write_header() {
  echo "" >> "$REPORT_FILE"
  echo "==============================" >> "$REPORT_FILE"
  echo "$1" >> "$REPORT_FILE"
  echo "==============================" >> "$REPORT_FILE"
}

write_line(){
echo "$1" >> "$REPORT_FILE"
}

write_header "System Report"
write_line "Generated by: $(whoami)"
write_line "Generated on: $(date)"


for SECTION in user date uptime disk memory current_directory git_status

do 

 case "$SECTION" in

	user)
	 write_header "Current User"
	 whoami >> "$REPORT_FILE"
	 ;;

	date)
	write_header "Date"
        date >> "$REPORT_FILE"
        ;;

       uptime)
       write_header "Uptime"
       uptime >> "$REPORT_FILE"
       ;;

      disk)
      write_header "Disk Usage"
      df -h >> "$REPORT_FILE"
      ;;

      memory)
      write_header "Memory Usage"
      free -h >> "$REPORT_FILE"
      ;;

      current_directory)
      write_header "Current Directory"
      pwd >> "$REPORT_FILE"
      ;;

      git_status)
      write_header "Git Status"

      if git rev-parse --is-inside-work-tree > /dev/null 2>&1
      then
        STATUS=$(git status --short)

        if [ -z "$STATUS" ]
        then
          echo "Working tree clean." >> "$REPORT_FILE"
        else
          echo "$STATUS" >> "$REPORT_FILE"
        fi
      else
        echo "Not inside a Git repo." >> "$REPORT_FILE"
      fi
      ;;

  esac
done

 write_header "Repeated Uptime Checks"

 COUNT=1

	while [ "$COUNT" -le 3 ]
	do
       echo "Check $COUNT:" >> "$REPORT_FILE"
       uptime >> "$REPORT_FILE"
       COUNT=$((COUNT + 1))
       sleep 1
       done

echo "System report generated at: $REPORT_FILE"
